(eval-when-compile
  (require 'color-theme))

(defun color-theme-greens ()
  "Color Theme by Gao Han."
  (interactive)
  (color-theme-install
   '(color-theme-greens
     ((foreground-color . "#007003")
      (background-color . "#000000")
      (cursor-color . "#961227"))
     (font-lock-builtin-face ((t (:foreground "#00876e"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#525b00"))))
     (font-lock-comment-face ((t (:foreground "#525b00"))))
     (font-lock-constant-face ((t (:foreground "#608329"))))
     (font-lock-doc-face ((t (:foreground "#6dbd1d"))))
     (font-lock-function-name-face ((t (:underline t :foreground "#15a000"))))
     (font-lock-keyword-face ((t (:underline t :foreground "#00876e"))))
     (font-lock-preprocessor-face ((t (:foreground "#525b00"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#6dbd1d"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "#6dbd1d"))))
     (font-lock-string-face ((t (:background "#0b1500" :foreground "#6dbd1d"))))
     (font-lock-type-face ((t (:foreground "#748747"))))
     (font-lock-variable-name-face ((t (:underline t :foreground "#608329"))))
     (font-lock-warning-face ((t (:underline t :foreground "#bcb820"))))
     (region ((t (:background "#007003" :foreground "#000000"))))
     (secondary-selection ((t (:background "#525b00" :foreground "#000000"))))
     (fringe ((t (:background "#000000" :foreground "#525b00"))))
     (vertical-border ((t (:foreground "#525b00"))))
     (highlight ((t (:inverse-video t))))
     (isearch ((t (:background "#d16500" :foreground "#000000"))))
     (lazy-highlight ((t (:underline t :foreground "#d16500"))))
     (isearch-fail ((t (:inherit font-lock-warning-face))))
     (ido-first-match ((t (:underline t :foreground "#d16500"))))
     (ido-only-match ((t (:underline t :foreground "#d16500"))))
     (ido-subdir ((t (:foreground "#00876e"))))
     (minibuffer-prompt ((t (:foreground "#748747"))))
     (mode-line ((t (:background "#007003" :foreground "#000000" :box (:line-width 1 :color "#007003")))))
     (mode-line-buffer-id ((t (:weight normal))))
     (mode-line-highlight ((t (:box (:line-width 1)))))
     (mode-line-emphasis ((t (:weight normal))))
     (mode-line-inactive ((t (:background "#525b00" :foreground "#007003" :box (:line-width 1 :color "#007003")))))
     (show-paren-match ((t (:background "#ffffff" :foreground "#000000"))))
     (show-paren-mismatch ((t (:background "#bcb820" :foreground "#000000"))))
     (tooltip ((t (:family "Telegrama" :background "#0b1500" :foreground "#ffffff"))))
     (linum ((t (:background "#000000" :foreground "#525b00"))))
     (ecb-default-highlight-face ((t (:background "#086078" :foreground "#007003"))))
     )))
