(eval-when-compile
  (require 'color-theme))

(defun color-theme-kuler ()
  "Color Theme by Gao Han."
  (interactive)
  (color-theme-install
   '(color-theme-kuler
     ((foreground-color . "#d1d1bc")
      (background-color . "#010712")
      (cursor-color . "#961227"))
     (font-lock-builtin-face ((t (:foreground "#632a56"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#474338"))))
     (font-lock-comment-face ((t (:foreground "#474338"))))
     (font-lock-constant-face ((t (:foreground "#a63e26"))))
     (font-lock-doc-face ((t (:foreground "#395443"))))
     (font-lock-doc-string-face ((t (:foreground "#395443"))))
     (font-lock-function-name-face ((t (:underline t :foreground "#ffffff"))))
     (font-lock-keyword-face ((t (:foreground "#414b73"))))
     (font-lock-negation-char-face ((t (:foreground "#961227"))))
     (font-lock-preprocessor-face ((t (:foreground "#474338"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#474338"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "#395443"))))
     (font-lock-string-face ((t (:foreground "#5b6b2b"))))
     (font-lock-type-face ((t (:foreground "#663f1b"))))
     (font-lock-variable-name-face ((t (:foreground "#968a10"))))
     (font-lock-warning-face ((t (:underline t :foreground "#961227"))))
     (region ((t (:background "#d1d1bc" :foreground "#010712"))))
     (secondary-selection ((t (:background "#474338" :foreground "#010712"))))
     (fringe ((t (:background "#010712" :foreground "#474338"))))
     (vertical-border ((t (:foreground "#474338"))))
     (highlight ((t (:inverse-video t))))
     (isearch ((t (:background "#d16500" :foreground "#000000"))))
     (lazy-highlight ((t (:underline t :foreground "#d16500"))))
     (isearch-fail ((t (:inherit font-lock-warning-face))))
     (ido-first-match ((t (:underline t :foreground "#968a10"))))
     (ido-only-match ((t (:underline t :foreground "#968a10"))))
     (ido-subdir ((t (:foreground "#414b73"))))
     (minibuffer-prompt ((t (:foreground "#5b6b2b"))))
     (mode-line ((t (:background "#d1d1bc" :foreground "#010712"))))
     (mode-line-buffer-id ((t (:weight normal))))
     (mode-line-highlight ((t (:box (:line-width -1)))))
     (mode-line-emphasis ((t (:weight normal))))
     (mode-line-inactive ((t (:background "#474338" :foreground "#d1d1bc" :box (:line-width -1 :color "#d1d1bc")))))
     (show-paren-match ((t (:background "#ffffff" :foreground "#000000"))))
     (show-paren-mismatch ((t (:background "#961227" :foreground "#000000"))))
     (tooltip ((t (:family "Telegrama" :background "#5b6b2b" :foreground "#000000"))))
     (linum ((t (:background "#010712" :foreground "#474338"))))
     (ecb-default-highlight-face ((t (:background "#632a56" :foreground "#d1d1bc"))))
     )))
